apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-model
spec:
  selector:
    matchLabels:
      app: gateway-model
  template:
    metadata:
      labels:
        app: gateway-model
    spec:
      containers:
      - name: gateway-model
        image: zoomcamp-10-gateway:v01
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9696
        env:
          - name: TF_SERVING_HOST
            value: tf-serving-clothing-model.default.svc.cluster.local:8500
